### PR TITLE
Fix typo unreasonable

### PR DESCRIPTION
**Pull request by maxnordlund**
Missing `le` in unreasonab**_le**_

### CODE REVIEW

**Comment by eliduke** [comment]
I'm guessing that some of the keywords intentionally leave off the end of them to apply to different endings. Like: unreasonable and unreasonably. There's a bunch of other "misspelled" words in the list as well: respon, sensitiv, nurtur... etc.

**Comment by maxnordlund** [comment]
Hm, then I guess that needs to be documented if it is like you said. I'll wait for @lovedaybrooke then

**Comment by lovedaybrooke** [comment]
Eliduke has it exactly right. I'm using these words as stems so I don't have to include all variants of reasonable/reasonably/etc

Sorry it took me so long to get around to responding.

**Comment by maxnordlund** [comment]
It's quite alright, ~~but maybe a comment would be prudent?~~

Edit: Made a PR with a comment, see #3

**Pull request closed without merging**
